import Navbar from "@/components/Navbar";
// import "../global.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard | Admin",
  description: "Generated by create next app",
};

export default function MyApp({ children }) {
  return (
    <>
      <main className={inter.className}>d{children}</main>
    </>
  );
}
